evolutionary:
	gcc ./evolutionary.c -o ./dist/evolutionary -lm && ./dist/evolutionary

localsearch:
	gcc ./localSearch.c -o ./dist/localsearch -lm && ./dist/localsearch

hybrid1:
	gcc ./hybrid_I.c -o ./dist/hybrid -lm && ./dist/hybrid
	
hybrid2:
	gcc ./hybrid_II.c -o ./dist/hybrid -lm && ./dist/hybrid

clean:
	rm ./dist/*